name: HideTag
main: Wantedkillerss\HideTag\Tag
version: 0.2
api: [1.10.0]
load: POSTWORLD
authors: [Wantedkillers (Author), SenorContento (Editor)]
website: github.com/PocketWarriors/hideTag

commands:
  hidetag:
    description: Hide your name
    usage: /hidetag
  unhidetag:
    description: Hide your name
    usage: /unhidetag
permissions:
  hidetag.command:
    description: "Hide oneself and unhide oneself"
    default: op